<!doctype html><html><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:12px;margin:28px}h1{margin:0 0 4px;font-size:22px}.muted{color:#667085}.summary{display:table;width:100%;margin:20px 0}.card{display:table-cell;border:1px solid #dfe4ea;padding:10px}.card strong{display:block;font-size:15px;margin-top:4px}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #e6e9ee;padding:8px 6px;text-align:left}th{background:#f4f6f8;font-size:10px;text-transform:uppercase}td.num,th.num{text-align:right}.debit{color:#b54708}.credit{color:#067647}.footer{margin-top:24px;border-top:1px solid #ddd;padding-top:10px}
</style></head><body>
<h1>Customer Credit Statement</h1><div class="muted">{{ $from }} to {{ $to }}</div>
<p><strong>{{ $customer->name }}</strong><br>{{ $customer->phone ?: $customer->email }}</p>
<div class="summary"><div class="card">Opening<strong>{{ number_format($opening,2) }} MMK</strong></div><div class="card">Purchases<strong>{{ number_format($purchases,2) }} MMK</strong></div><div class="card">Payments / credits<strong>{{ number_format($credits,2) }} MMK</strong></div><div class="card">Closing balance<strong>{{ number_format($closing,2) }} MMK</strong></div></div>
<table><thead><tr><th>Date</th><th>Reference</th><th>Type</th><th class="num">Debit</th><th class="num">Credit</th><th class="num">Balance</th></tr></thead><tbody>
@forelse($transactions as $entry)<tr><td>{{ $entry->created_at?->format('Y-m-d H:i') }}</td><td>{{ $entry->reference ?: $entry->transaction_number }}<br><span class="muted">{{ $entry->order?->order_number }}</span></td><td>{{ ucfirst($entry->type) }}</td><td class="num debit">{{ $entry->amount > 0 ? number_format($entry->amount,2) : '-' }}</td><td class="num credit">{{ $entry->amount < 0 ? number_format(abs($entry->amount),2) : '-' }}</td><td class="num">{{ number_format($entry->balance_after,2) }}</td></tr>@empty<tr><td colspan="6">No transactions in this period.</td></tr>@endforelse
</tbody></table><div class="footer muted">Store credit purchases and repayments are processed by authorized store staff. Please contact the store if a record is incorrect.</div>
</body></html>
